import { Button, VerticalBox } from "std-widgets.slint";
import { Logo } from "components/logo.slint";
import { FavList } from "components/fav-list.slint";
import { User } from "components/user.slint";
import { Title } from "components/title.slint";
import { PlayList } from "components/play-list.slint";
import { PlayControls } from "components/play-controls.slint";
import { FavListModel } from "types.slint";

export global MathHelper  {
    pure callback to_percent(float) -> percent;
}

export component AppWindow inherits Window {
    no-frame: true;
    width: 800px;
    height: 580px;

    property <bool> drag-area-pressed: false;
    property <length> drag-area-down-x: 0;
    property <length> drag-area-down-y: 0;

    callback move-window(length, length);
    callback minium-clicked();
    callback close-clicked();

    // user
    in-out property <bool> is-login: false;
    in-out property <image> qrcode;
    in-out property <bool> is-scan-qrcode: false;
    callback request-login();
    
    in-out property <int> user-id;
    in-out property <string> user-name: "Login";
    in-out property <image> user-image;
    in-out property <bool> is-vip: false;
    callback username-clicked();
    callback vip-clicked();

    // fav
    in-out property <[FavListModel]> fav-list;
    

    function process_move_event(i: int, ev: PointerEvent, is_pressed: bool, x: length, y: length) {
        if ev.kind == PointerEventKind.down {
            drag-area-down-x = x;
            drag-area-down-y = y;
            drag-area-pressed = true;
        } else if ev.kind == PointerEventKind.up {
            drag-area-down-x = x;
            drag-area-down-y = y;
            drag-area-pressed = false;
        } else if ev.kind == PointerEventKind.move && is_pressed {
            move-window(x - drag-area-down-x, y - drag-area-down-y);
        }
    }

    popup_qrcode := PopupWindow {
        close-policy: no-auto-close;

        x: 300px; y: 200px; height: 250px; width: 250px;
        visible: !is-login;

        Rectangle {
            width: 100%;
            height: 100%;
            background: #fafafa;
            border-radius: 10px;
            drop-shadow-blur: 5px;
            drop-shadow-color: #aaaab2;
            
            VerticalLayout {
                Rectangle {
                    height: 40px;
                    Text {
                        font-size: 15pt;
                        color: #fb7185;
                        TouchArea {
                            width: 100%;
                            height: 100%;
                            mouse-cursor: pointer;
                            clicked => {
                                popup_qrcode.close();
                            }
                        }
                        text: "close";
                    }
                }

                Image {
                    source: qrcode;
                }

                Rectangle {
                    height: 40px;
                    Text {
                        font-size: 15pt;
                        color: #fb7185;
                        text: is-login ? "login success" : (is-scan-qrcode ? "scanned qrcode" : "scan qrcode");
                    }
                }
            }
        }
    }

    public function show-login-qrcode() {
        popup_qrcode.show();
    }

    public function close-login-qrcode() {
        popup_qrcode.close();
    }

    Rectangle {
        width: parent.width;
        height: parent.height;
        border-width: 1px;
        border-color: #ccc;

        VerticalLayout {
            // width: 799px;
            // height: 579px;
            spacing: 0px;

            HorizontalLayout {
                width: parent.width;
                height: 519px;
                

                // left
                VerticalLayout {
                    width: 199px;
                    height: parent.height;
                    spacing: 0px;
                    
                    Rectangle {
                        TouchArea {
                            // window move area
                            pointer-event(ev) => {
                                process_move_event(0, ev, self.pressed, self.mouse-x, self.mouse-y);
                            }
                        }

                        // logo
                        width: parent.width;
                        height: 84px;

                        Logo {
                            width: parent.width;
                            height: parent.height;
                        }
                    }

                    Rectangle {
                        // fav list
                        width: parent.width;
                        height: 365px;

                        FavList {
                            fav-list: fav-list;
                            
                            width: parent.width;
                            height: parent.height;
                        }
                    }

                    Rectangle {
                        // divider
                        width: parent.width;
                        height: 1px;
                        background: #e4e4e7;
                    }

                    Rectangle {
                        // user
                        width: parent.width;
                        height: 69px;

                        User {
                            user-id: user-id;
                            user-name: user-name;
                            user-image: user-image;
                            is-vip: is-vip;

                            username-clicked => {
                                if is-login {
                                    username-clicked();
                                } else {
                                    show-login-qrcode();
                                    request-login();
                                }
                            }
                            vip-clicked => {
                                if is-login {
                                    vip-clicked();
                                } else {
                                    show-login-qrcode();
                                    request-login();
                                }
                            }
                        }
                    }
                }
                
                
                Rectangle {
                    // divider
                    width: 1px;
                    height: parent.height;
                    background: #e4e4e7;
                }

                VerticalLayout {
                    y: 1px;
                    width: 600px;
                    height: parent.height;
                    spacing: 0px;

                    Rectangle {
                        TouchArea {
                            // window move area
                            pointer-event(ev) => {
                                process_move_event(0, ev, self.pressed, self.mouse-x, self.mouse-y);
                            }
                        }

                        // title
                        width: 599px;
                        height: 48px;
                        background: white;
                        
                        Title {
                            minium-clicked => {
                                minium-clicked();
                            }
                            close-clicked => {
                                close-clicked();
                            }
                        }
                    }

                    Rectangle {
                        // divider
                        width: parent.width;
                        height: 1px;
                        background: #e4e4e750;
                    }

                    Rectangle {
                        // main
                        width: 599px;
                        background: white;
                    
                        PlayList {}
                    }
                }
            }

            Rectangle {
                // divider
                width: parent.width;
                height: 1px;
                background: #e4e4e7;
            }

            Rectangle {
                // bottom
                width: 798px;
                height: 59px;
                x: 1px;
                background: white;
                
                PlayControls {
                    to_percent(f) => {
                        MathHelper.to_percent(f);
                    }
                }
            }
        }
    }

    
    // VerticalLayout {
    //     width: 199px;
        
    //     Text {
    //         text: "Counter: \{root.counter}";
    //     }

    //     Button {
    //         text: "Increase value";
    //         clicked => {
    //             root.request-increase-value();
    //         }
    //     }
    // }
}